### ISSUE TITLE
Add link to this repo and vice-versa

### ISSUE THREAD

**Issue by waldyrious** [jakobw/wd-query-builder#4]
There should be a link on the tool's page (https://tools.wmflabs.org/wd-query-builder/) to this repository, and likewise, the README in the repo and the url (editable in the settings in the github interface) should link to the live tool page.

I can contribute the changes to the README and to the html page, but the repository settings can only be changed by the repo owner.

**Comment by jakobw** [comment]
Done! Thanks for pointing that out!

**Comment by waldyrious** [comment]
Thanks for the quick reaction :) Would you accept a PR adding a link to this repo so that it shows up in https://tools.wmflabs.org/wd-query-builder/? Perhaps at the bottom of the page or in one of the corners.

**Comment by jakobw** [comment]
Generally I'd be happy to accept PRs but I already sneakily put a note with a link up on https://tools.wmflabs.org/wd-query-builder/ earlier today without adding it to the repo itself.

**Comment by waldyrious** [comment]
Sure, that works :+1:
